#ifndef _parseerrors_h
#define _parseerrors_h

/* lex errors */
#define LEX_INVALID_NUMBER_FORMAT -1
#define LEX_UNEXPECTED_ESCAPE -2
#define LEX_UNTERMINATED_CHAR -3
#define LEX_UNTERMINATED_STRING -4
#define LEX_ERROR -5

/* parse errors */
#define YYER_EXPECTED_CLASS_DEF 1
#define YYER_EXPECTED_CLASS_NAME 2
#define YYER_OUT_OF_MEM 3
#define YYER_EXPECTED_SUPER_CLASS 4
#define YYER_EXPECTED_LBRACE 5
#define YYER_EXPECTED_RBRACE 6
#define YYER_EXPECTED_METHOD_NAME 7
#define YYER_EXPECTED_LPAR 8
#define YYER_EXPECTED_RPAR 9
#define YYER_EXPECTED_VAR_NAME 10
#define YYER_EXPECTED_SEMI 11
#define YYER_ASSIGN_SYNTAX 12
#define YYER_NEW_SYNTAX 13
#define YYER_EXPECTED_ARRAY_INDEX 14
#define YYER_EXPECTED_RBRAC 15
#define YYER_EXPECTED_COMMA 16
#define YYERR_SYNTAX 17
#define YYER_EXPECTED_ID 18
#define YYER_EXPECTED_COLON 19
#define YYER_EXPECTED_CATCH 20
#define YYER_UNKNOWN_CLASS 21
#define YYER_EXPECTED_SCOPE_OP 22
#define YYER_EXPECTED_ACCESS 23
#define YYER_UNKNOWN_METHOD 24
#define YYER_UNKNOWN_ID 25
#define YYER_ILLEGAL_STATIC_REF 26
#define YYER_INVALID_ARRAY_INDEX 27
#define YYER_INST_REF_IN_STATIC 28
#define YYER_EXPECTED_VAR_OR_CLASS 29
#define YYER_ILLEGAL_CASE_VALUE 30
#define YYER_ILLEGAL_ARRAY_INIT 31
#define YYER_METH_RETURNS_VAL 32

#endif

